exceljs/exceljs

- README.md
- lib/column.js
Hi,
I added documentation on how to hide rows and columns to the readme.  I found a use case for this in one of my apps and thought it'd be useful.
Also, I was going to add "hidden" as a property, but realized some conflicts could potentially occur with the "width" property.  I will create an issue for that.
> Added documentation about hiding rows and columns.

- README.md
- lib/workbook.js
- lib/worksheet.js
- lib/xlsx/sheet.xml
Hi,
in our project we need to create worksheets with different tab colors. I added a new parameter called "tabColor" to the "addWorksheet" function and added a new segment to the worksheet template.
> Worksheet Tab Color

- README.md
> Update README.md Typo fix

- README.md
- lib/doc/column.js
- lib/doc/row.js
- lib/xlsx/sheet.xml
Outline (group) data in a worksheet
> outline levels

- MODEL.md
- README.md
- lib/doc/worksheet.js
- lib/xlsx/sheet.xml
Ability to control print settings.
> Print settings

- lib/xlsx/xlsx.js
This is gen6033's idea
https://github.com/gen6033/exceljs/commit/faeb8670815dc909f8a904903a43e2acb73c235d
> Fix a bug on phonetic characters

- lib/stream/xlsx/workbook-writer.js
> Fix regression #150: Stream API fails to write XLSX files

- lib/doc/defined-names.js
- lib/utils/col-cache.js
- lib/xlsx/xform/book/defined-name-xform.js
- spec/unit/doc/defined-names.spec.js
- spec/unit/utils/col-cache.spec.js
@agdevbridge is the true author of these changes. I just applied these fixes to latest version.
> Changes from guyonroche/exceljs#127 applied to latest version

- lib/utils/shared-strings.js
- spec/integration/workbook-xlsx-writer.spec.js
> Do not escape xml characters when using shared strings

- lib/xlsx/xform/sheet/hyperlink-map.js
Please consider adding my code to the master branch. It would be a huge help.
> Fix tiny bug [Update hyperlink-map.js]

- lib/stream/xlsx/workbook-writer.js
- lib/utils/stream-buf.js
- spec/unit/utils/stream-buf.spec.js
Fix of https://github.com/guyonroche/exceljs/issues/198
> Fire finish event instead of end event on write stream

- lib/xlsx/xform/core/core-xform.js
This quick and dirty fix, which simply adds some fields, that, seems like to be putted to the resulting workbook. Since I have no idea how to skip those fields during parsing, I made this simple fix, which works perfectly for me.
> Fix issue #178

- lib/doc/workbook.js
- lib/stream/xlsx/workbook-writer.js
- lib/xlsx/xform/core/core-xform.js
- spec/unit/xlsx/xform/core/core-xform.spec.js
- spec/unit/xlsx/xform/core/data/core.03.xml
Hello,
Here is a pull request to fix #206. Please consider merging it to the master branch.
Thank you!
> Fix issue 206

- README.md
update to README.md to include an example of how to use hyperlink to reference an internal sheet
> Add a comment for issue #216

- lib/xlsx/xlsx.js
> Stops Bluebird warning about unreturned promise

- lib/xlsx/xform/sheet/data-validations-xform.js
- spec/utils/data/data-validations.json
Source: #252 
* make sure formulae is an array
* add example to spec
> [BUGFIX] data validation formulae undefined

- lib/xlsx/xform/core/core-xform.js
I ran into a similar issue to https://github.com/guyonroche/exceljs/issues/176, just for dc:identifier. I found the property in the spec, so I added it in this PR. Unfortunately I haven't been able to receive the file from the customer that ran into this (I only have the stacktrace), but I am trying to get it so I can create a test case.
> Add support for identifier

- lib/stream/xlsx/workbook-writer.js
- lib/xlsx/rel-type.js
- lib/xlsx/xlsx.js
This makes the workbook properties appear correctly on the properties window inside MS Excel.
Also tested in LibreOffice
> Add missing Office Rels

- lib/stream/xlsx/hyperlink-reader.js
- lib/stream/xlsx/workbook-reader.js
- lib/stream/xlsx/worksheet-reader.js
- lib/xlsx/xform/style/styles-xform.js
I needed to get streaming reads to work to handle very large workbooks, and ran into a few smaller issues.
I have kept the changes in separate commits, so it is easier to follow.
> Assortment of fixes for streaming read

- README.md
- lib/utils/zip-stream.js
- lib/xlsx/xlsx.js
> Add Base64 Image support for the .addImage() method

- lib/xlsx/xform/sheet/col-xform.js
- spec/integration/workbook-xlsx-writer/workbook-xlsx-writer.spec.js
> Fixes #458

- lib/xlsx/xform/simple/date-xform.js
Fix Issue #488 where dt is an invalid time format, catch the exception and return blank string.
>  Issue #488

- lib/doc/worksheet.js
- lib/stream/xlsx/workbook-writer.js
- lib/stream/xlsx/worksheet-writer.js
- lib/xlsx/workbook.xml
- lib/xlsx/xform/book/sheet-xform.js
- lib/xlsx/xform/book/workbook-xform.js
This PR can solve this issue https://github.com/guyonroche/exceljs/issues/226
> Sheet add state for hidden or show

- README.md
> Fix formatting issue in README

- index.d.ts
> Add type definition for Column.values

- index.d.ts
https://github.com/exceljs/exceljs/issues/792
> Update Worksheet.dimensions return type #792

- lib/xlsx/xform/drawing/two-cell-anchor-xform.js
> fix(image): fix editAs assignment

- package.json
Closes https://github.com/exceljs/exceljs/issues/825
> Publish lib/ and the modern entrypoints

- lib/doc/workbook.js
- spec/integration/worksheet.spec.js
- spec/utils/test-spliced-sheet.js
Addressing [Issue 398](https://github.com/exceljs/exceljs/issues/398).
> Only keep at most 31 characters for sheetname

- lib/xlsx/xform/style/styles-xform.js
- package.json
- spec/utils/test-spliced-sheet.js
- spec/utils/test-values-sheet.js
Font skipped each time, when `styleId===0`
related issues
https://github.com/exceljs/exceljs/issues/849
https://github.com/exceljs/exceljs/issues/833
https://github.com/exceljs/exceljs/issues/816
> Always keep first font

- index.d.ts
- lib/utils/zip-stream.js
- lib/xlsx/xlsx.js
- spec/integration/workbook/workbook.spec.js
Probably related: https://github.com/exceljs/exceljs/issues/847
> zip: allow tuning compression for performance or size

- README.md
- README_zh.md
- index.d.ts
- lib/doc/worksheet.js
- lib/xlsx/xform/sheet/header-footer-xform.js
- lib/xlsx/xform/sheet/worksheet-xform.js
- spec/unit/xlsx/xform/sheet/header-footer-xform.spec.js
Add new features to configure headers and footers.
Not support add image to headers and footers.
Maybe readme.md needs you to re-edit, my English is not good.
> Feat configure headers and footers

- lib/stream/xlsx/sheet-comments-writer.js
- lib/stream/xlsx/sheet-rels-writer.js
- lib/stream/xlsx/workbook-writer.js
- lib/stream/xlsx/worksheet-writer.js
- test/test-comment-stream-writer.js
when using stream.xlsx.WorkbookWriter adding a note to a cell will result in an exception.
The "issue" was documented in #868, but comments/notes were simply not introduced for the stream writter yet.
Please let me know if anything is needed on my end for this PR.
> Feature/Add comments/notes to stream writer

- README.md
@ABenassi87 Added doc for you change.
Ref. #889
> Add document for zip options of streaming WorkbookWriter

- README.md
Original section has been superseded by new section with v3.
> Remove outdated Importing section from README.md

- lib/xlsx/xform/sheet/cell-xform.js
> array formula

- README.md
- index.d.ts
> Add `shrinkToFit` to document and typing

- lib/xlsx/xform/table/table-xform.js
Verify that autoFilter.model exists before accessing.
> Fix issue #988

- README.md
- lib/xlsx/xform/book/workbook-xform.js
- test/testMultiplePrintAreaOut.js
Allows multiple print areas to be input per sheet by using a `&&` separator. 
E.g. `printArea = 'A1:G10&&A11:G20'`
> 1041 multiple print areas

- README.md
- README_zh.md
- index.d.ts
- lib/stream/xlsx/worksheet-writer.js
- lib/xlsx/xform/sheet/sheet-format-properties-xform.js
- lib/xlsx/xform/sheet/worksheet-xform.js
- spec/unit/xlsx/xform/sheet/sheet-format-properties-xform.spec.js
Added `defaultColWidth` as an optional property of `SheetFormatPropertiesModel`.
#1075
> Fix Issue #1075: Unable to read/write defaultColWidth attribute in <sheetFormatPr> node

- benchmark.js
- package.json
I believe it would be highly useful to have a way of running benchmarks, to understand how certain PRs impact performance. This PR adds an xlsx with 150k rows spread of 2 worksheets (data taken from http://eforexcel.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/) as well as a new `benchmark` task to our package.json.
Here are the numbers of the current `master` on node v13:
```
####################################################
WARMUP: Current memory usage: 8.6 MB
WARMUP: huge xlsx file profiling started
Reading worksheet 1
Reading row 50000
Reading row 100000
Reading worksheet 2
Reading row 150000
Processed 2 worksheets and 150002 rows
WARMUP: huge xlsx file profiling finished in 6830ms
WARMUP: Current memory usage (before GC): 63.35 MB
WARMUP: Current memory usage …
```
> Add benchmarking

- lib/xlsx/xform/sheet/worksheet-xform.js
- spec/unit/xlsx/xform/sheet/data/sheet.4.0.json
- spec/unit/xlsx/xform/sheet/worksheet-xform.spec.js
* fix for issue #1118 
*  conditionalFormattings must be before dataValidations
> fix issue #1118 Adding Data Validation and Conditional Formatting to the same sheet causes corrupt workbook

- package.json
This one should fix issues #997 and #971
> Update @types/node version to latest lts

- README.md
- README_zh.md
- index.d.ts
- lib/csv/csv.js
- spec/integration/workbook/workbook.spec.js
* Fix for issue #1165 
* Added configuration items supported by library [fast-csv](https://c2fo.io/fast-csv/)
> fix issue #1165 and update index.d.ts

- index.d.ts
fixes wrong typings : https://github.com/exceljs/exceljs/issues/1175
> fixes #1175

- index.d.ts
> fix issue #1178 and update index.d.ts

- .github/workflows/nodejs.yml
In according to: #1180 #1178 #1179 
I want to prevent similar situations like above 
I tested it before, and it works.
> Simple test if typescript is able to compile

- README.md
Typo in DataValidation examples
N/A
> Typo in DataValidation examples

- lib/stream/xlsx/worksheet-writer.js
- spec/integration/workbook-xlsx-writer/workbook-xlsx-writer.spec.js
- spec/utils/data/conditional-formatting.json
- spec/utils/index.js
- spec/utils/test-conditional-formatting-sheet.js
* fix for issue #1057 
* Support for conditional formatting in xlsx write streams
> fix issue #1057 Fix addConditionalFormatting is not a function error when using Streaming XLSX Writer

- README.md
- index.d.ts
> fix issue #1194 and update index.d.ts

- lib/xlsx/xform/sheet/data-validations-xform.js
- lib/xlsx/xform/style/style-xform.js
- spec/unit/xlsx/xform/style/data/styles.1.1.json
- spec/unit/xlsx/xform/style/data/styles.1.2.xml
- spec/unit/xlsx/xform/style/style-xform.spec.js
* The value of the `protection` attribute is not stored after reading the file.
* Fix for issue #1206 and #1205 .
> fix issue #1206 #1205 Abnormality of  and attributes

- lib/xlsx/xform/strings/shared-strings-xform.js
- spec/integration/issues/issue-703-speciel-cell-file.spec.js
* Fix special cell values causing invalid files produced.
* Fix for issue #703.
`issue-703-speciel-cell-file.spec.js`
> [bugfix] Fix special cell values causing invalid files produced

- package.json
Fixes https://github.com/exceljs/exceljs/issues/1313
@guyonroche could you please merge and release this?
> 4.0.1 - bundle all files

- README.md
- README_zh.md
Updated readme for insert rows with style
> Updated readme for insert rows

- index.d.ts
Hey,
#1337 everything is explained inside this issue. 
Trying to fix/help with this definition file.
> Fix: Async iterators defition

- lib/utils/shared-strings.js
- spec/integration/issues/issue-1339-speciel-cell-file.spec.js
Fix special cell values causing invalid files produced.
Fix for issue #1339 .
`issue-1339-speciel-cell-file.spec.js `
> [bugfix] Fix special cell values causing invalid files produced(#1339)

- index.d.ts
- package.json
#1357 
Fix styleOption error in index.ts
As typescript updates, errors occur where existing styleOption is omitted.
> Fix styleOption error in index.ts

- README.md
- README_zh.md
Modified documentation. Separated add rows and splice functions. Added api specs for them.
No additional testing needed.
> Improved documentation

- README.md
Images are not supported in streaming mode. The documentation should indicate this.
See #322, #351, #446
> README: images not supported in streaming mode

- lib/utils/col-cache.js
Doing a profiling in chrome dev tools shows that the function `decodeAddress` and `validateAddress` in `lib/utils/col-cache.js` are taking considerable amount of time, mainly on the cache lookup and regexp matching. This would make that faster, especally with large worksheets.
Existing unit test and `npm run benchmark` result below.
Env: Windows 10 x64, node.js 12.18.4 LTS x64
<details> 
<summary>npm run benchmark on master(a68209129a05b9ae37ca01ac705f84af76453088)</summary>
```
> exceljs@4.1.1 benchmark D:\UserData\projects\exceljs
> node --expose-gc benchmark
####################################################
WARMUP: Current memory usage: 8.89 MB
WARMUP: huge xlsx file streams profiling started
Reading worksheet 1
Reading row 50000
Reading row 100000
Reading worksheet 2
Reading row …
```
> col-cache: optimize for performance

- spec/integration/issues/issue-995-encoding.spec.js
I saw a few issues (#995, #1473) regarding CSV output encoding, and I wondered if it was working.
So I wrote a test... Turns out it is working.
> Add a test for CSV writeFile encoding

- README.md
> Update README.md(fix typo in a const name)

- index.d.ts
I want to fix types
Col:
https://github.com/exceljs/exceljs/blob/e1de62647ff92d64637f8c817f483605a8f69971/lib/doc/anchor.js#L40-L42
Row:
https://github.com/exceljs/exceljs/blob/e1de62647ff92d64637f8c817f483605a8f69971/lib/doc/anchor.js#L49-L51
No test found for types in this library
> Fix fullAddress row and col types

- index.d.ts
- lib/doc/workbook.js
Related to #1655 
Try to set Workbook's properties e.g. `workbook.title = 'some title';` should not  throw `TS2339`
> Add TS declarations of Workbook properties

- README.md
Current doc for cell filling could lead to misunderstanding on how to apply a simple fill color
to a cell.
Related to https://github.com/exceljs/exceljs/issues/272
No test required for a readme update.
> doc: add example for solid pattern usage

- lib/doc/worksheet.js
- spec/integration/issues/issue-2125-spliceRows-last-row.spec.js
https://github.com/exceljs/exceljs/issues/2125
test code
> fix issue 2125 - spliceRows remove last row

- index.d.ts
> fix: add spinCount field for WorksheetProtection type
