lib/csv/csv.js
lib/stream/xlsx/workbook-writer.js
lib/utils/flow-control.js
lib/utils/stream-buf.js
lib/utils/utils.js
lib/xlsx/stylemanager.js
lib/xlsx/xlsx.js

For this issue #48 
Promise.defer() is not part of the Promise API anymore:
https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred
```javascript
var deferred = Promise.defer();
doSomething(function cb(err, res) {
if (err) deferred.reject(err); else deferred.resolve(res);
});
return deferred.promise;
```
is now replaced to 
```javascript
return new Promise(function(resolve, reject) {
doSomething(function cb(err, res) {
if (err) reject(err); else resolve(res);
});
});
```

Promise.defer() replaced by new Promise(function(resolve, reject)

---

lib/stream/xlsx/workbook-reader.js
lib/utils/stuttered-pipe.js

These log messages appear in our automatic tests.
I notice you've used commented logs throughout. Would it be useful to you if I switched it over to `debug` so you can turn them on/off with env vars rather than comments? It's easy to forget to re-comment them, which I assume is why they're here!

some logs not commented out

---

lib/stream/xlsx/workbook-reader.js

sharedStrings initialized a second time by mistake. When "emit" option is selected, logic expects sharedStrings to still be null, not initialized to empty array. The result is that event never gets emitted.

stream.xlsx.WorkBookReader - Fixed issue that prevented 'shared-string' event being emitted when "emit" selected in options

---

lib/xlsx/xlsx.js

I encountered the following:
```
Unhandled rejection TypeError: Cannot read property 'target' of undefined
at .../node_modules/exceljs/lib/xlsx/xlsx.js:662:54
```
I traced this down to the fact that my Excel file contains a "chart sheet", which is missing from `model.workbookRels`. This guard allows the rest of the Excel file to be read.

Fix TypeError crash

---

README.md

The `commit()` method in case of Workbook returns a promise. The example in README now reflects that.

Improve workbook.commit() example.

---

lib/xlsx/xform/shared-string-xform.js

fix #120, which happens when adding a row with empty string:
```js
sheet.addRow({
bar: 'exceljs',
foo: ''
});
```

fix "read property 'richText' of undefined"

---

lib/xlsx/xform/style/style-xform.js

Integer cell values are interpreted as Dates based on `cellXfs.xf` elements in `xl/styles.xml`.  However, when any spreadsheet has "protected" cells, these `xf` elements can have the form:
```xml
<xf borderId="1" fillId="10" fontId="3" numFmtId="0" xfId="0" applyProtection="1" applyAlignment="1" applyFill="1" applyBorder="1" applyFont="1">
<alignment horizontal="center" vertical="center"/>
<protection locked="0"/>
</xf>
```
Currently, unknown child elements of `xf` elements are not handled correctly and this causes `xl/styles.xml` to be parsed incorrectly (this is the root of the problem).  When `xl/styles.xml` is parsed incorrectly, the `lib/xlsx/style/styles-xform.js` method `getStyleModel` can fail to find the `numFmt` for Date types.  The change here does not have to be "the fix" …

Protect cell fix

---

lib/stream/xlsx/workbook-writer.js

Views wheren't passed to worksheet-writer from workbook-writer.
If you wanted for example to define frozen columns or rows, this was not previously possible when using the Streaming I/O.
The handling for views already excised in the worksheet-writer, but the option simply wasn't passed.

Pass views to worksheet-writer

---

README.md
lib/xlsx/xform/sheet/sheet-view-xform.js
spec/integration/workbook.spec.js
spec/unit/xlsx/xform/sheet/data/sheet.1.3.json
spec/unit/xlsx/xform/sheet/data/sheet.1.4.json
spec/unit/xlsx/xform/sheet/sheet-view-xform.spec.js
spec/utils/data/views.json

According to the [documentation](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.sheetview.showgridlines(v=office.14).aspx) the showGridLines var in worksheet views options is misspelled. It should be "showGridLines", not "showGridlines".
I changed all the files, and now it is working.

fix typo on sheet view showGridLines option

---

lib/stream/xlsx/workbook-writer.js

Fix of https://github.com/guyonroche/exceljs/issues/198

Listen for finish event on zip stream instead of middle stream

---

lib/xlsx/sheet.xml
lib/xlsx/xform/sheet/row-xform.js
spec/unit/xlsx/xform/sheet/row-xform.spec.js

The "spans" attribute is not required in the "row" element. Source of information: https://msdn.microsoft.com/en-us/library/office/documentformat.openxml.spreadsheet.row.aspx
If we create a Google Sheets spreadsheet and download it as XLSX, then the "spans" attributes do not appear in the "row" elements of the worksheet.
Attached is a test xlsx file, which causes the "Cannot read property 'split' of undefined" error when trying to read it with the exceljs package.
[test-issue-163.xlsx](https://github.com/guyonroche/exceljs/files/542029/test-issue-163.xlsx)

Fix issue #163: the "spans" attribute of the row element is optional

---

lib/doc/row.js
lib/xlsx/xform/book/workbook-xform.js

Currently it is not possible to apply styles to an empty cell and have them rendered. The cell must be given a value to be included in the render. This means you cannot let text from one cell flow over in to an adjacent cell (left or right ) with styling.  This commit causes 1, possibly 2 tests to fail. I can (and will) make the tests pass fairly quickly. Is there any implication I am missing?

Allow styling of cells with no value.

---

lib/xlsx/xform/core/core-xform.js

Referring to #176 I still had errors thrown for the attributes dc:language and cp:revision when reading from .xlsx files created with LibreOffice. These changes fixed the issue for my use case. 
Please let me know if there is anything missing / should be optimized and I'll modify my PR.

Fix "Unexpected xml node in parseOpen" bug in LibreOffice documents for attributes dc:language and cp:revision

---

lib/stream/xlsx/worksheet-writer.js

I noticed that when using both "tabColors" and "sheetViews" the resulting xlsx files end up being corrupt when trying to open in Microsoft Excel. After playing around a bit in the zip files I realized Excel is pretty picky about element order in the xml files, and it prefers to have the Sheet Properties before the Sheet Views. 
Here is some example code that is corrupt before my change and opens fine after:
```var Excel = require('../exceljs/excel');
var wb = new Excel.stream.xlsx.WorkbookWriter({filename: "tabColorTest.xlsx", useSharedStrings: true});
var ws = wb.addWorksheet('blort', {
properties: {
tabColor: {argb: 'FFFF0000'}
},
views: [
{
state: 'frozen',
ySplit: 1,
topLeftCell:"A2"
}
]
});
ws.getCell('A1').value = "frozenHeader";
ws.getCell('A2').value = "tabColorTest";
wb.commit(); …
```

Fix output order of Sheet Properties

---

lib/doc/workbook.js
lib/stream/xlsx/workbook-writer.js

_worksheets are saved as a loose array with undefined item[0]
when counting number of worksheets in xform models the .length is used - includes item[0]
when inserting worksheets into xml then .forEach method is used - excludes item[0]
this results in docProps/app.xml with data for a workbook with a single worksheet `foo` like:
```
<TitlesOfParts>
<vt:vector size="2" baseType="lpstr">
<vt:lpstr>foo</vt:lpstr>
</vt:vector>
</TitlesOfParts>
```
error being in `vt:vector` of size 2 with only one item inside

remove empty worksheet[0] from _worksheets

---

lib/xlsx/xform/strings/shared-string-xform.js

when working with shared strings this library adds empty string into shared strings (as it should), but when the shared strings are processed into xml, the empty string is omitted
workbook with cells `['foo', '', 'bar']` creates `xl/sharedStrings.xml` like:
```
<sst xmlns="..." count="3" uniqueCount="3">
<si><t>foo</t></si>
<si/>
<si><t>bar</t></si>
</sst>
```
with missing `<t>` tag in `<si>`
this results in missing shared string in some excel reading libs that do not count this `<si>` as a string
when the sheet is opened and resaved with MS Excel, the shares string includes an empty `<t>` tag

do not skip empty string in shared strings so that indexes match

---

lib/stream/xlsx/workbook-writer.js

stream writer did not use shared strings even if the useSharedStrings option was enabled due to variable name mismatch between
- `WorkbookWriter` - `lib/stream/xlsx/workbook-writer.js:59` - `this.streamedValues`
- `WorksheetWriter` - `lib/stream/xlsx/worksheet-writer.js:454` - `self._workbook.sharedStrings`

use shared strings for streamed writes

---

lib/doc/workbook.js
lib/stream/xlsx/workbook-writer.js
lib/xlsx/xform/book/workbook-properties-xform.js
lib/xlsx/xform/book/workbook-xform.js
lib/xlsx/xlsx.js
spec/unit/xlsx/xform/book/data/book.1.1.json
spec/unit/xlsx/xform/book/data/book.1.2.xml
spec/unit/xlsx/xform/book/data/book.1.3.json
spec/unit/xlsx/xform/book/workbook-properties-xform.spec.js

This is just the bare minimum start for date 1904 support, but it is as much as I have time for right now.
It should apply to the parsing and formatting of dates, but I have not been able to figure out how to get the property passed into the date handling, so it can be accounted for.
It will also require more tests before it is ready to be merged in.
References #219

Start on support for 1904 based dates

---

lib/xlsx/xform/sheet/worksheet-xform.js

I was trying to convert a file that had both an hyperlink and data validations. For some obscure reason, Excel didn't want to open the resulting file. Putting the links after the data validations in the sheet's XML fixed the issue.
I'm not familiar enough with exceljs to write a test for this issue.

Sheets with hyperlinks and data validations are corrupted

---

lib/stream/xlsx/workbook-writer.js
lib/utils/zip-stream.js

I upgraded from 0.2.38 to 0.2.46 today, and a few of our testcases failed. I tracked it down to two issues:
* The catch handler on the zip parsing was missing, and also wasn't propagating the error via the event emitter.
* The workbook writer was resolving the write when the zip-stream was done, not when the underlying stream was done. This meant that the write could resolve, while f.ex. a file was still being written to disk.

Minor fixes for stream handling

---

lib/doc/workbook.js
lib/xlsx/xform/core/core-xform.js
spec/integration/workbook.spec.js
spec/unit/xlsx/xform/core/core-xform.spec.js
spec/unit/xlsx/xform/core/data/core.04.xml

This adds support for cp:contentStatus, which previously resulted in an Excel file with this core property set to fail to load.

Add support for cp:contentStatus

---

lib/utils/utils.js

See https://en.wikipedia.org/wiki/Valid_characters_in_XML - the previous PR (#262) stripped out the valid newline (\x09) and carriage return (\x0D) characters, although the test spec was correct.
Fix #207
Fix #274

Fix Valid characters in XML (allow \n and \r when saving)

---

lib/utils/col-cache.js
spec/unit/utils/col-cache.spec.js

This PR adds support for decoding references with an error. It does this by using a regex to find the sheetname, if any, and handle the optional quotes. I wish JS regex had named groups, in which case this would be a bit nicer.

Support error references in cell ranges

---

lib/xlsx/xform/sheet/worksheet-xform.js

We ran into an error on a specific sheet from a customer, where it failed because `medium` was undefined. This fixes it as such, but I am not sure it is the right way to handle it.
I also coulnd't figure out how best to add a test for this.

Avoid error on anchor with no media

---

lib/xlsx/xform/sheet/worksheet-xform.js

I found a sheet that didn't have an r:id set for a linked range, which caused it to fail. This simply ignores hyperlinks with no r:id for the hyperlinkMap

Don’t set address if hyperlink r:id is undefined

---

README.md
lib/doc/enums.js
lib/xlsx/xform/sheet/sheet-view-xform.js
lib/xlsx/xform/style/alignment-xform.js
spec/unit/xlsx/xform/sheet/data/sheet.1.3.json
spec/unit/xlsx/xform/sheet/sheet-view-xform.spec.js
spec/unit/xlsx/xform/style/alignment-xform.spec.js

Adds a new property to sheet view. And fixes `readingOrder` as it wasn't doing anything for 2 reasons:
1. The values were set wrong. 
2. The keys were `l2r` and `r2l` instead of the document `ltr` and `rtl` ones.
Closes #72
Closes #126

Fix right to left issues

---

lib/xlsx/xform/book/workbook-xform.js

cant open xlsx saved from Numbers
model.properties is undefined

Fix #345 TypeError: Cannot read property 'date1904' of undefined

---

README.md
lib/doc/row.js
lib/doc/worksheet.js
lib/xlsx/xform/sheet/page-breaks-xform.js
lib/xlsx/xform/sheet/row-breaks-xform.js
lib/xlsx/xform/sheet/worksheet-xform.js
spec/unit/doc/worksheet.pagebreak.spec.js
spec/unit/xlsx/xform/sheet/data/sheet.1.0.json
spec/unit/xlsx/xform/sheet/data/sheet.1.1.json
spec/unit/xlsx/xform/sheet/data/sheet.7.0.json
spec/unit/xlsx/xform/sheet/data/sheet.7.1.json
spec/unit/xlsx/xform/sheet/data/sheet.7.2.xml
spec/unit/xlsx/xform/sheet/page-breaks-xform.spec.js
spec/unit/xlsx/xform/sheet/worksheet-xform.spec.js

Hi Guyon,
Added a feature to enable inserting page breaks (#386).
**Note**: there are 2 args to `addPageBreak()` but I was unable to get them working satisfactorily, so I did not document the args (needed to move on).

Add rowBreaks feature.

---

lib/xlsx/xform/drawing/two-cell-anchor-xform.js
spec/unit/xlsx/xform/drawing/two-cell-anchor-xform.spec.js

I ran into an issue with the [`reconcile` method](https://github.com/guyonroche/exceljs/blob/master/lib/xlsx/xform/drawing/two-cell-anchor-xform.js#L108) of `TwoCellAnchorXform`. I can't provide the spreadsheet to give you a working demo of the issue, but I did find the problem and built a unit test to display the issue. Basically, `model.picture` might be null, which throws an error. Once I added the guards, I was able to load the workbook as usual.

Guard null model fields - fix and tests

---

README.md

Add some docs about importing scv to the stream.

Add some comments in readme according csv importing

---

README.md
lib/xlsx/xform/drawing/cell-position-xform.js
lib/xlsx/xform/drawing/two-cell-anchor-xform.js
package.json
spec/integration/workbook/images.spec.js
test/test-image-oneCell.js

It is not possible at the moment to store a image with an offset to tl and br.

Impl <xdr:twoCellAnchor editAs=oneCell>

---

lib/xlsx/xform/core/core-xform.js

I've run into an .xlsx that contains a `<cp:version>` tag in `docProps/core.xml`:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>...</dc:title><dc:creator>...</dc:creator><cp:lastModifiedBy>...</cp:lastModifiedBy><cp:lastPrinted>2017-05-15T16:17:00Z</cp:lastPrinted><dcterms:created xsi:type="dcterms:W3CDTF">2015-07-15T16:27:34Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2017-09-06T15:39:12Z</dcterms:modified><cp:version></cp:version></cp:coreProperties>
```
This …

Don't break when docProps/core.xml contains a <cp:version> tag

---

lib/utils/utils.js
spec/unit/utils/utils.spec.js

Hi,
while I was trying to test the generation of our excel file using your library, I found out that some date were not matching what I was expecting.
Opening my file in excel seem to display the correct value, but reloading it with the library and then comparing the excel value to what I was expecting was not always matching. By example writing the following date 2017-11-15T17:00:00.000Z to an excel file and then re-reading it would return 2017-11-15T16:59:59.999Z.
Since excel already round value to the millisecond when showing the value and a javascript date doesn't have precision under a millisecond, I would like to propose that we round the value to the nearest millisecond when reading an excel file.
I haven't found any mention of precision in the spec file, but I think it would be …

Round Excel date to nearest millisecond when converting to javascript date

---

lib/doc/workbook.js
spec/unit/doc/workbook.spec.js

wb._worksheets is an array with an empty first element. Calling wb.worksheets or wb.eachSheet called _worksheets.sort() which mutated the array and shifted the sheets into the empty element slot. I am not sure that the mutation was intentional or necessary. My solution no longer mutates _worksheets.
Also added test.

Bug fix: wb.worksheets/wb.eachSheet caused getWorksheet(0) to return sheet

---

.travis.yml

Hi @guyonroche,
I appreciate your work on this package! I use it regularly in different node environments, and I think using simple continuous integration would be very helpful for me (and possibly others) to understand this package's node compatibility, and for ensuring tests pass for pull requests and new features.
In a [previous PR](https://github.com/guyonroche/exceljs/pull/453) I've added a `.travis.yml` file that TravisCI can use. It's free of charge, and the good news is that the [tests pass in Node versions 6-9](https://travis-ci.org/cooltoast/exceljs/)!
Please consider activating this repo in TravisCI: https://docs.travis-ci.com/user/getting-started/
Upon the next pushed commit, it'll immediately build and run the tests you've written.
Thanks!

Add Node 8 and Node 9 to continuous integration testing

---

lib/xlsx/xform/sheet/cell-xform.js
spec/integration/workbook-xlsx-writer/workbook-xlsx-writer.spec.js
spec/unit/xlsx/xform/sheet/cell-xform.spec.js

- When streaming, render "richText" values as <c t="inlineStr"><is><r>...</r></is></c>
- Parse inlineStr values correctly, including plain text and rich text
This should fix #409 and hopefully also covers the case in #495.

Add support for inlineStr, including rich text

---

package.json

This allows TypeScript to automatically detect the types based on the file.

Include index.d.ts in published packages

---

lib/doc/row.js

I've run into an Excel spreadsheet where some `<c>` elements do not have address references. It looks like it's some kind of shorthand where it's implicitly the next cell, and Excel opens the spreadsheet fine. Here's a pretty-printed snippet from the spreadsheet:
```xml
<sheetData>
<row r="1" spans="1:1" ht="18" customHeight="1">
<c r="A1" s="1" t="s">
<v>0</v>
</c>
</row>
<row r="2" spans="1:1" ht="12.75" customHeight="1">
<c r="A2" s="2" t="s">
<v>1</v>
</c>
</row>
<row r="3" spans="1:1" ht="12.75" customHeight="1">
<c r="A3" s="2" t="s">
<v>2</v>
</c>
</row>
<row r="5" spans="1:12" ht="12.75" customHeight="1">
<c r="A5" s="4" t="s">
<v>51</v>
</c>
<c s="4" t="s">
<v>52</v>
</c>
<c s="4" t="s">
<v>53</v>
</c>
<c s="4" t="s">
<v>54</v>
</c>
...
```
Exceljs breaks with:
```
(node:3101) …
```

Try to handle the case where a <c> element is missing an r attribute

---

index.d.ts
lib/csv/csv.js
package.json
spec/browser/exceljs.spec.js

Added csv write buffer support. Update types to include `writeBuffer` and modify types so they can be used for both browser and node installations.

Add CSV write buffer support

---

spec/integration/workbook-xlsx-reader.spec.js

Looks like https://github.com/guyonroche/exceljs/commit/095c82faa238f91c72e4dee92d33939b9c9065f1 broke an essential feature of the [maxRows PR](https://github.com/guyonroche/exceljs/pull/541). It is delaying the [teardown of the stream](https://github.com/peakon/exceljs/blob/1ef6b6026b4eb80bbf4c8790e52638e91c3287ba/lib/xlsx/xform/base-xform.js#L69-L76) to the next tick by moving it to `promise.catch(...)` here: https://github.com/guyonroche/exceljs/commit/095c82faa238f91c72e4dee92d33939b9c9065f1#diff-678e4bd9f1bcf0cc0c17eee7684618abR101
That means that the parser will still busyloop on the remaining rows of the current unzipped chunk, which can be quite a lot.
I've added a test with a huge .xlsx that runs for over 30 seconds on my machine, but less than a second when I revert the tidy …

Add test case with a huge file

---

README.md

row.addPageBreak() adds a Page Break below the row and not prior to it as mentioned in the README. Updated the description accordingly.

Update README.md to reflect correct functionality of row.addPageBreak()

---

lib/xlsx/xform/core/core-xform.js
spec/unit/xlsx/xform/core/core-xform.spec.js
spec/unit/xlsx/xform/core/data/core.06.xml

I ran into a weird spreadsheet that claims it was generated by [Apache POI](https://poi.apache.org/). It is missing the `cp:` namespace for the `<cp:coreProperties>` element:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<coreProperties xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<dcterms:created xsi:type="dcterms:W3CDTF">2018-05-08T14:56:50Z</dcterms:created>
<dc:creator>Apache POI</dc:creator>
</coreProperties>
```
which makes exceljs die with:
```
Error: Unexpected xml node in parseClose: coreProperties
at …
```

core-xform: Tolerate a missing cp: namespace for the coreProperties element

---

lib/utils/col-cache.js
spec/unit/utils/col-cache.spec.js

Hi, I've run into another weird Excel file that causes an error in exceljs:
```
TypeError: Cannot read property '0' of null
at Object.decodeAddress (/Users/andreaslind/work/exceljs/lib/utils/col-cache.js:95:33)
at Object.decodeEx (/Users/andreaslind/work/exceljs/lib/utils/col-cache.js:156:21)
at /Users/andreaslind/work/exceljs/lib/xlsx/xform/book/workbook-xform.js:182:34
at Array.forEach (<anonymous>)
at Object.each (/Users/andreaslind/work/exceljs/lib/utils/under-dash.js:7:13)
at module.exports.reconcile (/Users/andreaslind/work/exceljs/lib/xlsx/xform/book/workbook-xform.js:175:7)
at module.exports.reconcile (/Users/andreaslind/work/exceljs/lib/xlsx/xlsx.js:91:19)
at /Users/andreaslind/work/exceljs/lib/xlsx/xlsx.js:345:16
at <anonymous>
```
The error is triggered by this …

Avoid error on malformed address

---

index.d.ts

In response from #548:
Fixed a typo in index.d.ts where stream.xlsx.workbook.commit()  is said to return void rather than Promise<void> as it does in the code and doc.
(I believe it could also be marked as returning Promise<WorkbookWriter> but I'm not fluent enough with Promish to state that with certainty.
As the documentation currently does not talk about return value beyond the promise, I believe that's a question for another day...)

Added a missing Promise<void> in index.d.ts

---

lib/xlsx/xform/sheet/worksheet-xform.js

I had an issue with adding both images and a pagebreak to a worksheet. Adding them independently was fine but adding them both together result in a corrupt document. 
The issue was related to the ordering of the elements. drawing must be below rowBreaks as seen here:
https://stackoverflow.com/a/12221477/4564456
You can also see the ordering of all the other elements there in case this comes up with new features. Moving drawing and picture below rowBreaks fixes the issue.
I'm currently blocked until this is merged so please let me know if there's anything else I can do to help! :)
Thanks

drawing element must be below rowBreaks according to spec or corrupt worksheet

---

lib/stream/xlsx/workbook-reader.js
package.json

when stream read some xlsx files (like numbers convert to xlsx),  get values like :
row.values [ ,
{ sharedString: 47 },
{ sharedString: 35 },
{ sharedString: 47 },
{ sharedString: 37 },
{ sharedString: 37 },
{ sharedString: 37 },
{ sharedString: 37 },
{ sharedString: 37 },
{ sharedString: 37 },
]
try to fix this problem

Fix some xlsx stream read xlsx not in guaranteed order problem

---

README.md
lib/doc/cell.js
lib/xlsx/xform/sheet/cell-xform.js
lib/xlsx/xform/sheet/hyperlink-xform.js

Hail! 
In MS Excel it is possible to [set a screen tip](https://www.addictivetips.com/microsoft-office/set-custom-hyperlink-tool-tip-text-in-ms-excel/) for a hyperlink. Pull-request adds a similar capability to ExcelJS.
Thanks!

Ability to set tooltip for hyperlink

---

README.md

Had to look for this in the source, would have been helpful to have it in the docs.
Updated the README to mentioned the load() option based on the comment here: https://github.com/guyonroche/exceljs/issues/167#issuecomment-310272619

Update README.md with load() option

---

index.d.ts

It is currently possible, when passing a formula as a value, to omit the result of the formula, and the result will be computed later.
`sheet.getCell("B1").value = { formula: 'SUM(A1:A6)' };`
This PR aims to add this possible syntax to the TypeScript module resolution file.

Add Typescript support for formulas without results

---

lib/stream/xlsx/workbook-reader.js
package.json

Right we are using the `temp` package for creating temp files to cache shared strings in the workbook reader. The problem is that the `temp` uses a global cache to keep track of its files, which is not safe for concurrent operation. In particular, the cleanup of one task will delete all files tracked globally, incl. those still needed by another task. This results in a node error that a file was not found.
In this PR we replace the `temp` to `tmp` which is safe for concurrent operations.

Replace the temp lib to tmp

---

lib/doc/worksheet.js
spec/integration/workbook/workbook.spec.js
spec/unit/doc/worksheet.values.spec.js
spec/utils/test-spliced-sheet.js

This PR fixes the style issues reported in https://github.com/exceljs/exceljs/issues/305 and https://github.com/exceljs/exceljs/issues/697 to copy over any existing styles already applied to rows. I have also included additional tests for this fix.

Fix existing row styles when using spliceRows

---

README.md
index.d.ts
lib/xlsx/xform/style/font-xform.js
spec/unit/xlsx/xform/style/vertical-aligment-xform.spec.js

Add support vertical align property (vertAlign) with possible values are superscript and subscript.
Related to #555 
Use:
for entire cell
`
firstRow.font = { name: 'Arial', family: 2, size: 20, vertAlign: 'superscript'}
`
rich text:
`
worksheet.getCell('A10').value = {
'richText': [
{'font': {'size': 12,'color': {'theme': 1},'name': 'Calibri','family': 2,'scheme': 'minor'},'text': 'This is '},
{'font': {'italic': true,'size': 12,'color': {'theme': 1},'name': 'Calibri','vertAlign': 'superscript'},'text': 'superscript'},
{'font': {'size': 12,'color': {'theme': 1},'name': 'Calibri','family': 2,'scheme': 'minor'},'text': 'and '},
{'font': {'italic': true,'size': 12,'color': {'theme': 1},'name': 'Calibri','vertAlign': 'subscript'},'text': 'subscript'},
]
};
`

Add vertical align property

---

README.md
index.d.ts
lib/xlsx/xform/drawing/drawing-xform.js
lib/xlsx/xform/drawing/ext-xform.js
lib/xlsx/xform/drawing/one-cell-anchor-xform.js
spec/integration/workbook/images.spec.js
test/test-image-one-cell-anchor.js

Addresses #738 #650 and is related to #702.
There is a bug in `cell-position-xform.js` that assumes that columns are 640,000 EMU wide and 180,000 EMU tall. This assumption is broken if you customise cell width or height, and the bug appears if you use fractional columns or rows to try to position your image.
This PR adds support for adding images using just a `tl` and then providing an `ext` that contains a `width` and `height` in pixels. The width and height are converted internally to EMU using a conversion at 96dpi. That _seems_ to be the right thing to do, but something I'm a little unsure about!
This change _should_ read as well as write the one-cell-anchor-xform, although I have only used writing so far but there is a test for reading and writing.

Add support for adding images anchored to one cell

---

.travis.yml

https://github.com/nodejs/Release
| Release  | Status              | Codename    |Initial Release | Active LTS Start | Maintenance LTS Start | End-of-life               |
| :--:     | :---:               | :---:       | :---:          | :---:            | :---:                 | :---:                     |
| [6.x][]  | **Maintenance LTS** | [Boron][]   | 2016-04-26     | 2016-10-18       | 2018-04-30            | 2019-04-30                |
| [8.x][]  | **Maintenance LTS** | [Carbon][]  | 2017-05-30     | 2017-10-31       | 2019-01-01            | December 2019<sup>1</sup> |
| [10.x][] | **Active LTS**      | [Dubnium][] | 2018-04-24     | 2018-10-30       | April 2020            | April 2021                |
| [11.x][] | **Current Release** |             | 2018-10-23     | …

Drop node version v6, add support to node v11 and v12

---

README.md
nodejs.js

Since we're about to add async/await, let's give node.js users a way to import our code directly, without getting the transpiled version. Otherwise, it will be much slower and produce worse stack traces.

Add an entrypoint for node.js

---

README.md

- Added the missing `font.size` to the property list
- Removed duplicated entries in `fill.pattern`
- Fixed title level of "Rich Text" section

docs(README): improve documentation

---

README.md
lib/config/set-value.js
lib/csv/csv.js
lib/stream/xlsx/workbook-writer.js
lib/utils/flow-control.js
lib/utils/promise.js
lib/utils/promish.js
lib/utils/stream-buf.js
lib/utils/utils.js
lib/utils/zip-stream.js
lib/xlsx/xform/base-xform.js
lib/xlsx/xform/simple/date-xform.js
lib/xlsx/xform/style/styles-xform.js
lib/xlsx/xlsx.js
modern.browser.js
modern.nodejs.js
nodejs.js
spec/config/setup-unit.js
spec/integration/issues/issue-266-breaking-bluebird.spec.js
spec/integration/workbook/images.spec.js
spec/unit/utils/stream-buf.spec.js

To make the most of async/await (performance & stack traces), we need to use the native Promises. This PR does not change that the default export uses `promish`, but it does add two new exports that allow access to the modern codebase and native promises. I've also fixed a couple of eslint failures in the affected files.
```javascript
const Excel = require('exceljs/modern.nodejs');
import Excel from 'exceljs/modern.browser';
```

Do not use a promise polyfill on modern setups

---

lib/xlsx/xform/sheet/sheet-format-properties-xform.js
spec/unit/xlsx/xform/sheet/data/sheet.1.2.xml
spec/unit/xlsx/xform/sheet/data/sheet.2.2.xml
spec/unit/xlsx/xform/sheet/data/sheet.3.2.xml
spec/unit/xlsx/xform/sheet/data/sheet.5.2.xml
spec/unit/xlsx/xform/sheet/data/sheet.6.2.xml
spec/unit/xlsx/xform/sheet/data/sheet.7.2.xml
spec/unit/xlsx/xform/sheet/sheet-format-properties-xform.spec.js

https://github.com/exceljs/exceljs/issues/696
https://github.com/exceljs/exceljs/issues/634
https://github.com/exceljs/exceljs/issues/422

Fix defaultRowHeight not working

---

index.d.ts
lib/stream/xlsx/workbook-writer.js
spec/integration/workbook-xlsx-writer/workbook-xlsx-writer.spec.js
test/testWbStreamCompressionOptions.js

Changes:
- Added zip options for `WorkbookWriterOptions` based on `archiver` docs.
- Added `testWbStreamCompressionOptions.js` test.
- Added 'with zip compression option' integration test.
- Updated `index.d.ts` with the new interfaces.
Note:
https://github.com/archiverjs/node-archiver allows setting the compression level of zip files. I added this option to `stream.xlsx.WorkbookWriter`
Resolves #888

Add Compression level option to WorkbookWriterOptions for streaming #888

---

index.d.ts

This pull request attempts to resolve issue #925 (typescript definitions for Worksheet.protect() and Worksheet.unprotect() have no explicit return values).
I understand that the readme file asks for tests for any bug fixes, however, I couldn't find any tests in place dealing with the TypeScript definitions file.

added explicit return types to the type definitions of Worksheet.protect() and Worksheet.unprotect()

---

.eslintrc
.gitignore
.prettier
gruntfile.js
lib/csv/csv.js
lib/exceljs.browser.js
lib/exceljs.nodejs.js
lib/stream/xlsx/sheet-rels-writer.js
lib/stream/xlsx/workbook-writer.js
lib/utils/flow-control.js
lib/utils/stream-buf.js
lib/utils/zip-stream.js
lib/xlsx/xform/base-xform.js
lib/xlsx/xlsx.js
package.json
spec/browser/exceljs.spec.js

Here it comes! 🎉 
In this PR, I've not modified any tests so that we know that these changes are a pure refactoring.
Unfortunately, `async` uses the internal `Promise` object and we cannot offer our users to use a different Promise library. To be backwards compatible with promish, I've added babel polyfill, but I would expect that most consumers of this library will start to use the modern entrypoints.
Looking forward to your feedback!

Introduce async/await 

---

lib/doc/anchor.js

It doesn't work when you have the address with nativeCol = 0

Fix anchor.js

---

lib/xlsx/xform/sheet/worksheet-xform.js
spec/unit/xlsx/xform/sheet/data/sheet.1.3.json
spec/unit/xlsx/xform/sheet/data/sheet.5.3.json
spec/unit/xlsx/xform/sheet/data/sheet.6.3.json

Fix #999 
I just added `headerFooter` to the model of `WorkSheetXform` in `#parseClose()`, in order that `Worksheet` object has `headerFooter` property read from existing xlsx file.
Even when `sheetX.xml` doesn't contain `<headerFooter>` node, `Worksheet` object still has `headerFooter` property with value `null`; I wonder whether this behavior is good.
Please let me know if anything is needed for this PR.

Add headerFooter to worksheet model when importing from file

---

package.json

grunt-contrib-jasmine has used Headless Chromium since v2.0.0.
https://github.com/gruntjs/grunt-contrib-jasmine#release-history
> 2018-05-19 v2.0.0 Switch from PhantomJS to Chrome Headless via Puppeteer
Thus we don't need phantomjs.

Drop grunt-lib-phantomjs

---

lib/exceljs.browser.js

This affects angular. Because core-js is imported inside the library , the Promise  polyfill is in conflict with  zone.js. Since Excel.js puts browsers compatibility on the hands of the devs. ([link](https://github.com/exceljs/exceljs#es5-imports)) , we can add it manually in a way that does not conflict with Angular.
this PR should fix : https://github.com/exceljs/exceljs/issues/1008
This was fixe din many other package and is referenced here:
angular/zone.js#783

     remove core-js/ import

---

index.d.ts
package.json

There were issue that cell comments are accessible by Cell.note property, but in index.d.ts were "comments" instead of "note".

fix typings for cell.note

---

README.md

The previous examples for merging cells by row/column numbers were confusing and didn't actually describe what parameters the function was expecting. The example made it appear that `mergeCells(10, 11, 12, 13)` was the same as `mergeCells("G10", "H11")`, which is not the case. This example has been updated as well as another comment added.

Clarify merging cells by row/column numbers

---

README.md

This PR fixes a couple of small inaccuracies in `README.md` concerning freezing views.
Just to explain one of the changes: In the "create a sheet with the first row and column frozen" code example, the code doesn't work as currently written. It needs the `state` property too.
Thanks for this excellent package!

Fix README mistakes concerning freezing views

---

lib/doc/workbook.js
spec/integration/worksheet.spec.js

1.The sheet name of the excel file created in the windows system is not case sensitive. But the ```workbook.addWorksheet ()``` method does not do the corresponding processing, This PR fixes issues caused by case of sheet names.
2.fix for #1064

Fix problems caused by case of worksheet names

---

lib/utils/stream-buf.js
lib/utils/zip-stream.js
spec/integration/workbook/workbook.spec.js
spec/unit/utils/stream-buf.spec.js

Since https://github.com/exceljs/exceljs/pull/829 `StreamBuf.write` returns Promise, that leads to unhandled promise rejection in `Workbook.load` because `ZipStream.write`do not expect `StreamBuf.write` to return Promise.

Prevent from unhandled promise rejection durning workbook load

---

index.d.ts

* Replace empty "Stream" interface with the Node internal "stream.Stream" interface
* Replace empty "Writable" interface with the Node internal "events.EventEmitter" interface
When using the library with TypeScript, I noticed that a couple of empty interfaces were causing errors in the TS parsing. I checked the source code and verified the correct internal interfaces so that the typings are accurate.
I know unit tests are required for PRs, but I don't see anywhere in this project that it has unit tests for the TypeScript definition, and I'm not really sure how to do that (or if it would even be useful). Let me know if I'm wrong!

Update TS definition to reference proper internal libraries

---

lib/utils/stream-buf.js

And it looks like we need to treat it as StringChunk
You can check the problem here https://codesandbox.io/s/file-upload-in-react-7ibtx

Support ArrayBuffer as an xlsx.load argument

---

lib/xlsx/xform/sheet/cell-xform.js
spec/unit/xlsx/xform/sheet/cell-xform.spec.js

This PR is intended to fix https://github.com/exceljs/exceljs/issues/633.
When an Excel file is read, a shared string with rich text (`<r>`) nodes inside is correctly parsed and reconciled into a `CellXform` object like below.
```js
{
model: {
value: { richText: [ ... ] },
type: Enums.ValueType.RichText,
},
}
```
However, `XLSX#writeFile()` converts this object into an empty cell in the exported Excel file, because `CellXform#prepare()` and `#render()` do nothing when `model.type === Enums.ValueType.RichText`.
To fix this, the both methods now handle `RichText` in the same way as `String`.

Export shared strings with RichText

---

lib/doc/worksheet.js
spec/integration/workbook/workbook.spec.js

#1101 Fix height for duplicateRows to match the height in the original row, it also fix a bug in spliceRows with the same behaviour (Ignoring row heights).

Fix to issue #1101  

---

lib/xlsx/xform/base-xform.js

Just a typo I came across - we could also use a totally different variable name, if someone has a better suggestion

Typo: Replace 'allways' with 'always'

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

Building on https://github.com/exceljs/exceljs/pull/1112, here are my suggestions for the PR, Feature Request and Question github templates.
Again, they are heavily inspired by https://github.com/facebook/jest/tree/master/.github - but there's one big difference: They don't want the github issue tracker to be used for questions, which are instead handled via discord, stackoverflow, etc. What is our stance here? 
We could encourage users to open issues to ask questions but warn them that they might not get answered (but then where should they go). Or we could ask them to use this only for clear bug reports or feature requests and direct them elsewhere (but where). What do you think?

Add PR, Feature Request and Question github templates

---

gruntfile.js
package.json

Uglify can not handle ES6+, such as `const` and `let`. Some npm dependencies, like `saxes`, can not be used without replacing uglify with the more modern terser because they publish modern JS.

Replace uglify with terser

---

README.md
README_zh.md

``hyperlink`` should be set like this:
```javascript
// internal link
worksheet.getCell('A1').value = { text: 'Sheet2', hyperlink: '#\'Sheet2\'!A1' };
```

fix issue #749 Fix internal link example errors in readme

---

lib/xlsx/xform/drawing/base-cell-anchor-xform.js
spec/integration/workbook/images.spec.js

* fix for issue #731 
* The cause of this issue #731 is that the suffix of the picture is uppercase letters,which causes the regular match to fail. The drawing1.xml file is not generated when the xlsx file is rewritten, so I personally think that the suffix name should not be case sensitive.

fix issue #731 image extensions not be case sensitive

---

lib/xlsx/xform/sheet/cell-xform.js

I kept getting the following error while deleting rows from a sheet: `Shared Formula master must exist above and or left of clone`.
I needed to know what cell it was complaining about, so I have changed it to: `Shared Formula master must exist above and or left of clone for cell <cell address>`
It's just a change in text in the error so not sure if it needs a test?

Include cell address for Shared Formula master must exist.. error

---

lib/doc/column.js
spec/integration/workbook-xlsx-writer/workbook-xlsx-writer.spec.js
spec/unit/doc/column.spec.js

* When user-defined column properties, but the column width is not set, we should set a default value for the column box.
* Fix for issue #204 .

fix issue #204 sets default column width

---

README.md
lib/doc/worksheet.js
test/test-protection-spinCount.js

The iteration count controls how many times the hash is applied. It is a mechanism for fine-tuning according to how much computation is desired. This is especially useful to future-proof against increasingly powerful computers (you can simply increase the iteration count). It is therefore natural to expose this as a setting to the developer.
In my use case, I use this library for generating web application downloads, and protecting each worksheet in the workbook caused a download delay of several seconds. I would like to be able to lower the iteration count.
```
const time1 = new Date();
await sheet.protect("password");
const time2 = new Date();
await sheet.protect("password", { spinCount: 1000 });
const time3 = new Date();
console.log(`Delta 1: ${time2 - time1}`); // < 1 second …
```

Allow user specified iteration count

---

README.md
README_zh.md
lib/csv/csv.js
lib/xlsx/xlsx.js

As discussed in https://github.com/exceljs/exceljs/pull/1135, let's deprecate `createInputStream` in favour of the `read` methods in 4.0

Deprecate createInputStream

---

package.json

This finally resolves #882
I've checked the changelog and none of the breaking changes affect us. `tmp` is also still compatbile with node v8, it just bumped its minimum requirement to the latest version of v8 to satifsfy its linter.

Upgrade tmp

---

gruntfile.js

Fixed [BUG] Invalid regular expression: /^[ -íŸ¿î€€-ï¿½ð€€-ô¿¿]$/: Range out of order in character class.
This was due to terser wrongly converting characters inside string literals.
Ref: https://github.com/terser/terser/issues/410
Tried new min js. Works fine. No such issue exists.

Fixed #1276

---

README_zh.md

I re-translated the simplified Chinese document (zh-cn) by myself. The following are the reasons why I did this:
- When I used the `xlsx` package in my project, I encountered that exporting xlsx files could not add styles (it is said to be only available in the pro version). I found` exceljs` as an alternative and it was very easy to use.
- I found a Chinese document (#834 ) while viewing the document, but after reading it, I found it very disappointing, and the traces of machine translation are also obvious.
Therefore, I plan to re-translate to avoid misleading others. I am not a professional translator, but the documents will be corrected manually sentence by sentence. Due to the limitations of my personal level, errors inevitably occur. However, I can guarantee that most of them are …

Re-translation of simplified Chinese documents (zh-cn)

---

.github/workflows/asset-size.yml
package.json

This PR adds a Github Action that runs on PRs that compares the build output asset sizes with master. This way, it is much easier to notice if a PR adds considerable size to the library.
This should help with issues like https://github.com/exceljs/exceljs/issues/1236 in the future.
It looks like this in action:
https://github.com/mydea/exceljs/pull/2

Compare asset sizes on pull requests

---

README.md
README_zh.md
lib/exceljs.browser.js
package.json

It adds 20KB to the build, which not everyone needs
See https://github.com/exceljs/exceljs/issues/1236

Do not include IE11 fix by default, let the users import it when needed

---

README.md

#1215
This reverts commit f65592e6dd5b1a1a1ef61c0c6cba29111a35b40e.
[Demo](https://github.com/strdr4605/exceljs/blob/jump2header/README.md#importing)
Also, in another branch, there is a version with different emoji
[Demo2](https://github.com/strdr4605/exceljs/blob/jump2header2/README.md#importing)
So if you like another option I can update this PR

Revert "add spaces before jump to header links"

---

lib/xlsx/xform/strings/shared-string-xform.js
spec/unit/xlsx/xform/strings/shared-string-xform.spec.js

* Fix cell.text return an empty object when cell is empty.
* Fix issue for #1299 .
`spec/unit/xlsx/xform/strings/shared-string-xform.spec.js`

Fix cell.text return an empty object when cell is empty

---

index.d.ts

Using `const enum` in .d.ts files breaks compilation with `--isolatedModules`. Instead, normal `enum`s have been used where a corresponding object exists at runtime. `PaperSize` does not exist at runtime, and so has been left as `const enum` for backwards compatibility.
This also adds a declaration for `ErrorValue` since it exists at runtime but had no TS definition. This does result in some duplication with `CellErrorValue`, but changing `CellErrorValue` to use `ErrorValue` would be a breaking change.
A comparable fix and explanation for the problem with using `const enum` can be found at https://github.com/chalk/chalk/pull/296, and some further explanation at https://ncjamieson.com/dont-export-const-enums/ and [this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23002 …

Remove const enum and add ErrorValue in index.d.ts

---

lib/doc/row.js
spec/integration/pr/test-pr-1334.spec.js

Fix the error that comment does not delete at spliceColumn
**Test Source Code**
```javascript
const Excel = require('./lib/exceljs.nodejs');
(async () => {
const wb = new Excel.Workbook();
const ws = wb.addWorksheet('testSheet');
ws.addRow(['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8']);
const row = ws.getRow(1);
row.getCell(1).note = 'test1';
row.getCell(2).note = 'test2';
row.getCell(3).note = 'test3';
row.getCell(4).note = 'test4';
ws.spliceColumns(2, 1);
await wb.xlsx.writeFile('data.xlsx');
})();
```
**Existing Results**
**Result**

Fix the error that comment does not delete at spliceColumn

---

index.d.ts

The ColorScaleRuleType should accept an array of Colours instead of a singular Colour.
TypeScript currently complains when providing an array of colours as part of a colour scale conditional formatting rule. This PR fixes the type definition to allow for an array of colours.
Before  
After

Change typing for colorScale colour to array of colours

---

lib/stream/xlsx/workbook-reader.js
spec/integration/pr/test-pr-1431.spec.js

Fix bug #1431 
Create worksheet with rich text, use the streaming reader to read it in and ensure you receive richText back.
`spec/integration/pr/test-pr-1431.spec.js`

Fix issue #1431 Streaming WorkbookReader _parseSharedStrings doesn't handle rich text within shared string nodes

---

gruntfile.js
lib/exceljs.browser.js
package.json

Previously grunt build would transpile the output of browserify to transpile all dependencies, but this would make some dependencies, such as core-js, unexpectedly transpiled. Also, this way of transpiling would create source maps only targeting the browserify output instead of original source, and makes the final `dist/exceljs.js` larger than expected.
* Fix Symbol.toString() related errors on IE11 caused by transpiling core-js
* Reduce size for compiled dist
* Keep original source maps before browserify
Existing ci builds and manually tested in browser.
<details>
<summary>screenshot of source map</summary>
</details>

grunt: skip babel transpile for core-js

---

lib/utils/under-dash.js
lib/utils/utils.js

We saw some performance issues in https://github.com/exceljs/exceljs/issues/742 that this PR tries to solve
Both helpers are already tested, this just refactors their implementation.

Increase the performance of some xml and html helpers

---

lib/utils/col-cache.js

Certain XLSX files have references to "TRUE" and "FALSE" that get ultimately passed over to the col-cache l2n method. When l2n is passed a string of 4 characters or more, it ends up regenerating the dictionary from scratch each time.
For a particular XLSX file I was working with, this change resulted in an overall 2x performance improvement. 
This change doesn't affect behavior, as `l2n` already throws when it encounters a string which is out of range. This change makes it throw earlier- before repopulating a 16384-length array each time.

Performance improvement in col-cache

---

index.d.ts

The `DefinedNamesRanges` type actually has a `ranges` property, not a `range` property. 
This is the code that populates the named ranges list: https://github.com/exceljs/exceljs/blob/master/lib/doc/defined-names.js#L143
As you can tell the field is named `ranges`, not `range`

Fix type definition for DefinedNamesRanges

---

lib/xlsx/xform/sheet/data-validations-xform.js
spec/integration/issues/issue-1027-sheet-defined-data-validate.spec.js

Fixed undefined ref error when setting a data validation that is a range of cells at the worksheet level
In the case where a data validation is set at the worksheet level with a range of cells "A1:A100" the error `Cannot set property 'marked' of undefined` would occur.
From what I could tell the original code would call `const addr = colCache.decodeAddress(dv.address);` this would return the value "A1" in the case of the following "A1:A100". Later on in the code it would try to mark "A1" `dvMap[otherAddress].marked = true;`, but in the dvMap it would be "A1:A100" and the error occurs.
I changed decodeAddress to decodeEx so that we can detect if the address is a single cell vs a range(dimension?). If a  dimensions property exist on the return object from decodeEx, it will shortcircuit and …

Fixed undefined ref error when setting a data validation that is a range of cells at the worksheet level

---

README.md
README_zh.md

Add the corresponding papersize for A3 to improve the document.
I didn't see any unit tests about papersize, so I didn't add unit tests, but I think Microsoft's excel file specifications are the same.
I only tested the papersize of A3. [Reference documents](https://docs.microsoft.com/zh-cn/office/vba/api/excel.xlpapersize)
The origin of the problem. #1406

add A3 paperSize number

---

lib/doc/worksheet.js
spec/unit/doc/worksheet.merge.spec.js

Merges aren't preserved when cells containing merges get overwritten after row inserts. Instead, the value of a merged cell gets applied to all cells in the merge separately.
| A1 and B1 | C1 |
|---|---|
| merged cell text || 
becomes
| A1 | B1 | C1 |
|---|---|---|
| merged cell text | merged cell text ||
This is because the values for the previously merged cells are pulled from the source row (`rSrc.values` in `spliceRows`). The source row's values repeat the merged value for each cell in the merge. For example, the source row values for the row in the first table would be `["merged cell text", "merged cell text"]`. These values are what gets applied to the cells in the destination row (`rDst`), and the merge is lost.
The extra lines I wrote in `spliceRows` to fix this reapply merges to …

Merge cells after row insert

---

lib/utils/browser-buffer-decode.js
lib/utils/browser-buffer-encode.js
lib/utils/parse-sax.js
lib/utils/zip-stream.js
lib/xlsx/xlsx.js

Doing a profiling in chrome dev tools shows that the `Buffer.toString()` and `Buffer.from(string)` is using unexpected long cpu time. With the native TextDecoder and TextEncoder it can get much faster in browsers supporting it.
On browsers not supporting TextDecoder, like Internet Explorer, this would fallback to original `Buffer.toString()` and `Buffer.from(string)`.
This implements almost the same of https://github.com/exceljs/exceljs/pull/1458 in a non monkey-patching way covering xlsx only.
Closes https://github.com/exceljs/exceljs/pull/1458
References:
https://github.com/feross/buffer/issues/268
https://github.com/feross/buffer/issues/60
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
Profiling below is based …

xlsx: use TextDecoder and TextEncoder in browser

---

index.d.ts

This PR is to refine the type definition for `Column`. This should resolve https://github.com/exceljs/exceljs/issues/1120
I derived this by looking at `column.js`. Then I replaced `index.d.ts` in `node_modules/exceljs` with my changes and the typescript issue from https://github.com/exceljs/exceljs/issues/1120 went away.

Refine typing for Column

---

lib/doc/worksheet.js
spec/integration/gold.spec.js
spec/integration/pr/test-pr-1487.spec.js

As suggested by @Jigna-Rathod in #1453, a `lastColumn` property is added in this PR.
I created an automated test in `gold.spec.js`.

Add lastColumn property (fixes #1453)

---

README.md

This is a docs improvement. It notes that the `encoding` option is for `workbook.csv.writeFile`, and not `workbook.csv.write`.
The motivation is that the encoding option wasn't fully clear which methods it applied to. See also #1473.
N/A
This change is extremely minor... I can add it to #1495 if wanted, since they're both related to this `encoding` option.

Clarify `encoding` option is just for `.writeFile`

---

index.d.ts

Using typescript the Table function `addRow` has a `rowNumber` parameter which is required but should be optional.
In the implementation https://github.com/exceljs/exceljs/blob/master/lib/doc/table.js#L341 there is a checks for undefined. And described in the comment above `either insert at rowNumber or append`

Typing Table add row optional rowNumber

---

index.d.ts
spec/integration/worksheet.spec.js

This PR updates the typescript definition file to have the correct return type for getRows. 
As you can see from this file https://github.com/exceljs/exceljs/blob/d76dc388d6b0914262feff24eb6386d4c030e4bb/lib/doc/worksheet.js#L352 when the range is < 1 it will return undefined.
I have also added a unit test to demonstrate that when the range is < 1 it returns undefined

Fixed return type on getRows

---

index.d.ts

Using typescript the FillPattern the `fgColor` should be optional.
This is described in the documentation https://github.com/exceljs/exceljs/blame/master/README.md#L1722

Typing FillPattern fgColor should be optional

---

index.d.ts

As detected as missing in #1453, the lastColumn property has its type defined in this PR.

Add type definition for lastColumn property (fixes #1453)

---

.github/workflows/exceljs.yml

v16 is a new major version of Node.js, let's make sure to add test case of this.
Related to (at least) issue #1594

Added Node v16 to the test suite

---

README.md
README_zh.md

I just changed "moment" to "dayjs".

Readme moment to dayjs

---

package.json

Snyk found a Denial of Service vulnerability in jszip: https://security.snyk.io/vuln/SNYK-JS-JSZIP-1251497
There is no version of exceljs so far upgrading to a safe version of jszip. This pull request is meant to solve that.
Run `npm install` and `npm test` after upgrading. All tests passed.

Upgrade jszip to its latest version to date. This version does not have any vulnerability found by Snyk so far

---

.github/workflows/tests.yml

FEAT https://github.com/exceljs/exceljs/issues/2237
In this PR:
* Added node versions 18 and 19 to the tests suite
* Drop node v8 tests

ExcelJS/ExcelJS#2237 : Update CI Tests, Drop support for Node v8 

---

lib/doc/workbook.js
spec/integration/worksheet.spec.js

As for worksheet name, it raises error if worksheet name contains followings characters now
```js
'*', '?', ':', '/', '\\', '[', ']'
```
I expect this implementation prevents worksheet from breaking
But, if these characters are full-width characters, the worksheet is broken
https://user-images.githubusercontent.com/3395349/187575650-5528a378-755e-46ae-a3fa-d12925aee154.mov
So, I fixed the issue
Code example is below
```js
import ExcelJS from 'exceljs';
const workbook = new ExcelJS.Workbook()
workbook.addWorksheet('？')
```
If error raises, the test is success

add characters cannot be used for worksheet name

---

README.md

In README.md, currently "Streaming XLSX" links to wrong place

README.md to have correct link for Streaming XLSX

---

lib/exceljs.browser.js

Added a polyfill of promise.finally to support lower version firefox.
When i use exceljs on firefox of v61.0.1 , the promise.finally api will be undefined.
Original promise api on firefox of v61.0.1：

Added a polyfill of promise.finally to support lower versions of Firefox.

---

lib/doc/anchor.js

The anchor.js assign `this.worksheet = worksheet` at end of constructor, but the getter (such as rowHeight) used in constructor will read this.worksheet. so it will cause rowHeight fall back to default value (180000);
When I want to add a image in a cell over a range, and I adjust the height of this row before. The nativeRowOff will not calculate use the row height.
```javascript
const Excel = require('exceljs');
const fs = require('fs').promises;
(async () => {
const workbook = new Excel.Workbook();
await workbook.xlsx.readFile('./test.xlsx');
const worksheet = workbook.getWorksheet(1);
const row = worksheet.getRow(1);
row.height = 400;
const col = worksheet.getColumn('A');
col.width = 200
const image = await fs.readFile('./image.png')
const imageId = workbook.addImage({
buffer: image, …
```

Fix read this.worksheet before assign it

---

package.json

This patches the zipslip vulnerability in <= 3.7.1 and patched in >= 3.8.0.
No issues found with our usage in https://stuk.github.io/jszip/CHANGES.html, most notable change was 3.9.0 API change, but we are unaffected, due to not using constructor arguments.
Run npm install and npm test after upgrading. All tests passed.

chore: upgrade jszip to ^3.10.1

---

README.md

spelling issue: **becouse** changed to **because**

fixed spelling error in README.md file

---

lib/xlsx/xlsx.js
spec/integration/pr/test-pr-2244.spec.js

When `await workbook.xlsx.writeFile(filename).`
was reported, but the error was not caught by try catch, after modifying the source code, it can now be caught
```
try {
const imageId2 = workbook.addImage({
buffer: fs.readFileSync('path/to.image.png'),
extension: 'png',
});
await workbook.xlsx.writeFile(filename);
} catch (error) {
console.log(error)
}
```

fix: Fix xlsx.writeFile() not catching error when error occurs

---

lib/doc/workbook.js
lib/doc/worksheet.js
spec/integration/worksheet.spec.js

This PR aims to resolve #2243 issue. 
Additionally, I transferred the responsibility for name validation from `Workbook` to `Worksheet`, which allowed me to tighten the rules for changing the name using: `ws.name`
I completed the missing tests and covers all new assertions.

Improve worksheets' naming validation logic.

---

.gitignore
lib/doc/column.js

https://github.com/exceljs/exceljs/blob/eec76a1d4e01e634d2fd9b3d2030cd36a0f2add4/spec/unit/xlsx/xform/sheet/sheet-properties-xform.spec.js#L43
https://github.com/exceljs/exceljs/blob/eec76a1d4e01e634d2fd9b3d2030cd36a0f2add4/lib/stream/xlsx/worksheet-writer.js#L532
https://github.com/exceljs/exceljs/blob/eec76a1d4e01e634d2fd9b3d2030cd36a0f2add4/lib/xlsx/xform/sheet/worksheet-xform.js#L302

Fix: Sheet Properties Types

---

index.d.ts

Super simple extension of the `CellHyperlinkValue` to include the `tooltip` functionality, which already was implemented (just the typing was missing).

Add missing tooltip attribute to CellHyperlinkValue index.d.ts

---

lib/utils/xml-stream.js

Updates the xml-stream.js to generate a single string instead of multiple strings for each attribute or record of attributes.
Closes: #2303

Increase resilience to generating large workbooks

---

index.d.ts
lib/xlsx/xform/style/border-xform.js

Several type definition has been fixed. Details:
- `Worksheet.lastColumn` can be `undefined` for an empty worksheet, as `Worksheet.lastRow` can be `undefined`.
- `date1904` should be an optional property for both `CellFormulaValue` and `CellSharedFormulaValue`.
- `CellFormulaValue.result` and `CellSharedFormulaValue.result` should include `boolean`.
- `CellFormulaValue.result` and `CellSharedFormulaValue.result` should include `CellErrorValue`, not `{ error: CellErrorValue }`, because `CellErrorValue` itself is already an interface with `error` as its property.
- `Protection` should have a `hidden` property, as is recorded in the documentation.
- `dashed` should be a valid value for `BorderStyle`, as is documented in ISO/IEC 29500-1:2016 18.18.3 ST_BorderStyle (Border Line Styles).
- …

fix: fix type definitions about last column, formula values and protection

---

index.d.ts

The `values` field for Column class is actually mutable.
https://github.com/exceljs/exceljs/issues/514#issuecomment-1782927522

#514: Remove invalid readonly for Column.values

---

index.d.ts
lib/doc/table.js
test/test-table.js

A continuation of https://github.com/exceljs/exceljs/pull/1907 with an added test and updates typings to allow for styles to be set in the column definition of a table
In a project that is using exceljs as a dependency, i took the following steps:
1. Navigated to `node_modules/exceljs/lib/doc/table.js`
2. Made the change in the PR here `cell[key] = style[key]` => `cell.style[key] = style[key]`
3. Added a column with the following format to my table `{ name: 'Column Name', totalsRowFunction: 'sum', style: { numFmt: '0.00%' } }`
4. Regenerated the report and confirmed that the colum was formatted as `0.00%'`
https://github.com/exceljs/exceljs/blob/master/lib/doc/table.js#L183-L189

fix: table column style bug and addTable colum type
